[package]
name = "bbmicro"
version = "0.1.0"
authors = ["Beta Bytes"]
edition = "2018"

[dependencies]
rand = "0.8.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.sdl2]
version = "0.34.3"
features = ["image", "mixer"]